OUTPUT_TOOLS += $(OUTPUT_BINDIR)pscd-new$(EXEPOST)
OUTPUT_TOOLS_OBJS +=
TOOLS_PSCD_NEW_SRCS = toolsrc/pscd-new/pscd-new.c
TOOLS_PSCD_NEW_INCS =

$(OUTPUT_BINDIR)pscd-new$(EXEPOST): $(TOOLS_PSCD_NEW_SRCS) $(TOOLS_PSCD_NEW_INCS)
	$(NATIVE_CC) -o $@ -Wall -Wextra $(TOOLS_PSCD_NEW_SRCS) $(NATIVE_CFLAGS) $(NATIVE_LDFLAGS)

