OUTPUT_TOOLS += $(OUTPUT_BINDIR)iso2raw$(EXEPOST)
OUTPUT_TOOLS_OBJS +=
TOOLS_ISO2RAW_SRCS = toolsrc/iso2raw/iso2raw.c
TOOLS_ISO2RAW_INCS =

$(OUTPUT_BINDIR)iso2raw$(EXEPOST): $(TOOLS_ISO2RAW_SRCS) $(TOOLS_ISO2RAW_INCS)
	$(NATIVE_CC) -o $@ $(TOOLS_ISO2RAW_SRCS) $(NATIVE_CFLAGS) $(NATIVE_LDFLAGS)

