OUTPUT_TOOLS += $(OUTPUT_BINDIR)elf2psx$(EXEPOST)
OUTPUT_TOOLS_OBJS +=
TOOLS_ELF2PSX_SRCS = toolsrc/elf2psx/elf2psx.c
TOOLS_ELF2PSX_INCS =

$(OUTPUT_BINDIR)elf2psx$(EXEPOST): $(TOOLS_ELF2PSX_SRCS) $(TOOLS_ELF2PSX_INCS)
	$(NATIVE_CC) -o $@ $(TOOLS_ELF2PSX_SRCS) $(NATIVE_CFLAGS) $(NATIVE_LDFLAGS)

